from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from .config import load_config
from .utils import read_json, write_json


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate KPI and threshold trade-off report."
    )
    parser.add_argument("--config", default="configs/config.yaml", help="Config file path.")
    parser.add_argument(
        "--predictions-csv",
        default=None,
        help="Path to predictions.csv generated by evaluate.py. Defaults to latest file.",
    )
    parser.add_argument(
        "--benchmark-json",
        default=None,
        help="Optional real-time benchmark JSON to include latency estimate.",
    )
    parser.add_argument(
        "--output-dir",
        default="artifacts/metrics/business",
        help="Output directory for KPI artifacts.",
    )
    return parser.parse_args()


def _resolve_latest_predictions_csv(metrics_root: str | Path) -> Path:
    root = Path(metrics_root)
    candidates = sorted(
        root.glob("*/predictions.csv"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        raise FileNotFoundError(
            f"No predictions.csv found under metrics root: {metrics_root}"
        )
    return candidates[0]


def _compute_tradeoff_table(predictions: pd.DataFrame) -> pd.DataFrame:
    class_mapping = predictions[["y_true_label", "y_true_index"]].drop_duplicates()
    drowsy_rows = class_mapping[
        class_mapping["y_true_label"].str.upper() == "DROWSY"
    ]
    if drowsy_rows.empty:
        raise ValueError("Unable to detect DROWSY class from predictions CSV.")

    drowsy_index = int(drowsy_rows.iloc[0]["y_true_index"])
    all_indices = sorted(predictions["y_true_index"].unique())
    if len(all_indices) != 2:
        raise ValueError("Business KPI utility requires binary classification outputs.")
    negative_index = min(all_indices)
    positive_index = max(all_indices)

    rows: list[dict[str, float]] = []
    y_true = predictions["y_true_index"].to_numpy(dtype=int)
    y_score = predictions["y_score_positive_class"].to_numpy(dtype=float)

    for threshold in np.linspace(0.10, 0.90, 17):
        y_pred = np.where(y_score >= threshold, positive_index, negative_index)

        actual_drowsy = y_true == drowsy_index
        actual_natural = ~actual_drowsy
        predicted_drowsy = y_pred == drowsy_index

        true_positive_drowsy = np.logical_and(actual_drowsy, predicted_drowsy).sum()
        false_positive_drowsy = np.logical_and(actual_natural, predicted_drowsy).sum()

        drowsy_total = int(actual_drowsy.sum())
        natural_total = int(actual_natural.sum())

        drowsy_recall = (
            float(true_positive_drowsy / drowsy_total) if drowsy_total > 0 else 0.0
        )
        false_alarm_rate = (
            float(false_positive_drowsy / natural_total) if natural_total > 0 else 0.0
        )
        overall_accuracy = float((y_pred == y_true).sum() / len(y_true))
        alert_rate = float(predicted_drowsy.sum() / len(y_true))

        rows.append(
            {
                "threshold": float(round(threshold, 2)),
                "drowsy_recall": drowsy_recall,
                "false_alarm_rate": false_alarm_rate,
                "overall_accuracy": overall_accuracy,
                "alert_rate": alert_rate,
                "score_recall_minus_false_alarm": drowsy_recall - false_alarm_rate,
            }
        )

    tradeoff = pd.DataFrame(rows)
    tradeoff.sort_values("threshold", inplace=True)
    return tradeoff


def generate_business_kpi_report(args: argparse.Namespace) -> dict[str, Any]:
    config = load_config(args.config)
    predictions_path = (
        Path(args.predictions_csv)
        if args.predictions_csv
        else _resolve_latest_predictions_csv(config["paths"]["metrics_dir"])
    )
    if not predictions_path.exists():
        raise FileNotFoundError(f"Predictions CSV not found: {predictions_path}")

    predictions = pd.read_csv(predictions_path)
    required_columns = {
        "y_true_index",
        "y_true_label",
        "y_score_positive_class",
    }
    missing = required_columns.difference(predictions.columns)
    if missing:
        raise ValueError(f"Predictions CSV missing required columns: {sorted(missing)}")

    tradeoff = _compute_tradeoff_table(predictions)
    best_row = tradeoff.sort_values(
        "score_recall_minus_false_alarm", ascending=False
    ).iloc[0]

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    tradeoff_csv = output_dir / "threshold_tradeoff.csv"
    kpi_report_json = output_dir / "kpi_report.json"
    tradeoff.to_csv(tradeoff_csv, index=False)

    benchmark_latency_ms: float | None = None
    if args.benchmark_json:
        benchmark_payload = read_json(args.benchmark_json)
        if "avg_inference_latency_ms" in benchmark_payload:
            benchmark_latency_ms = float(benchmark_payload["avg_inference_latency_ms"])

    kpi_report = {
        "source_predictions_csv": str(predictions_path),
        "selected_threshold": float(best_row["threshold"]),
        "selected_metrics": {
            "drowsy_recall": float(best_row["drowsy_recall"]),
            "false_alarm_rate": float(best_row["false_alarm_rate"]),
            "overall_accuracy": float(best_row["overall_accuracy"]),
            "alert_rate": float(best_row["alert_rate"]),
        },
        "latency_ms_from_benchmark": benchmark_latency_ms,
        "notes": {
            "false_alarm_rate_definition": "Predicted DROWSY while true label is NATURAL, normalized by NATURAL count.",
            "alert_rate_definition": "Predicted DROWSY ratio across all samples.",
            "threshold_selection_objective": "maximize(drowsy_recall - false_alarm_rate).",
        },
    }
    write_json(kpi_report_json, kpi_report)

    return {
        "tradeoff_csv": str(tradeoff_csv),
        "kpi_report_json": str(kpi_report_json),
        "selected_threshold": float(best_row["threshold"]),
    }


def main() -> None:
    args = parse_args()
    result = generate_business_kpi_report(args)
    print("Business KPI report generated.")
    for key, value in result.items():
        print(f"- {key}: {value}")


if __name__ == "__main__":
    main()

